### ISSUE TITLE
Comparison with pdfkit

### ISSUE THREAD

**Issue by dandv** [manuels/hpdf.js#11]
How does this library compare with [pdfkit](https://www.npmjs.com/package/pdfkit)?

**Comment by manuels** [comment]
Well, it solves the same problem.
However, hpdf.js was developed only with the browser in mind, not nodejs.

**Comment by dandv** [comment]
Thanks Manuel. Is this package still maintained? I see the last commit was more than 2 years ago.

**Comment by manuels** [comment]
Well, not really. I ported it a while ago, but I moved my focus to other projects because the lack of interest of other developers. pdfkit looks more healthy as a project.

**Comment by dandv** [comment]
Thanks. I'm [choosing between pdfkit and jsPDF now](https://github.com/devongovett/pdfkit/issues/367).
