### ISSUE TITLE
Fast on Linux but slow on Mac

### ISSUE THREAD

**Issue by 6Beaufort** [manuels/hpdf.js#15]
we use hpdf.js serverside in a node.js application. With server running under Linux the PDF generation is fast. Under MacOS Sierra is much slower (5 times I would guess). Machine performance is more or less comparable. Mac activity monitor does not indicate heavy CPU or RAM usage while generating PDF. 
Any idea what could be the reason for the different behavior?

**Comment by manuels** [comment]
Sorry, no idea. I guess the underlying question is why is nodejs so much slower on MacOS?

**Comment by 6Beaufort** [comment]
node is not slow on Mac in general. The rest of the application behaves comparably fast to Linux.

While generating PDFs, It looks like something is waiting. Loadmonitpr shows more or less normal 90% load in the first phase of generation, then a phase where nothing seems to happen and then the write and display phase. 
![aktivitatsanzeige alle prozesse 2017-02-23 08-06-46](https://cloud.githubusercontent.com/assets/1757613/23248384/69b59290-f99f-11e6-899f-2283aea64d03.jpg)

**Comment by 6Beaufort** [comment]
I ran the hpdf.js demos now and they are all pretty fast on Mac as well. So I guess the slowdown is located somewhere else after the pdf generation and hpdf.js is not causing it.
