### ISSUE TITLE
Feature Request: Ability to import existing PDF would be great

### ISSUE THREAD

**Issue by jdarling** [manuels/hpdf.js#3]
One thing missing in EVERY library I come across that deals with PDF's is the ability to import an existing PDF.  I have been trying to find a way to simply import, fill in the new stuff, and export the updated PDF for a while now.

Is there something overly difficult with this that I'm missing, or does it exist and I just can't find/figure it out :)

**Comment by manuels** [comment]
This library is a JS version of libharu (http://libharu.org/).
libharu doesn't support it, so hpdf.js also doesn't support it either.
