### ISSUE TITLE
demo page doesn't work

### ISSUE THREAD

**Issue by Abromeit** [manuels/hpdf.js#5]
> http://manuels.github.com/hpdf.js/

Accordeon-Boxes don't expand. 
(And BoxContent is empty when i want to expand it by myself via FireBug)

FireFox 26.0

**Comment by manuels** [comment]
Thanks for reporting this issue. I do not really maintain this package anymore since I created https://github.com/manuels/texlive.js. Maybe I'll fix it when I have time ;)

**Comment by ichpuchtli** [comment]
it's just the version of jQuery referenced , the page was designed to use jQuery 1.8.23 so but the CDN has push the latest version which breaks backwards comparability 

```
<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
```

to  

```
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
```

References
http://stackoverflow.com/questions/14524289/browser-is-undefined-error
https://developers.google.com/speed/libraries/devguide?csw=1#jquery

**Comment by manuels** [comment]
Great work @ichpuchtli!
Thanks, I fixed it.
