### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by ichpuchtli** [manuels/hpdf.js#6]
The demo page doesn't show any pdf's for at least IE9 and up, it seems like the base64 content is being produced but the pdf viewer doesn't show. Is it working for anyone / does the officially support any IE versions?

**Comment by ichpuchtli** [comment]
Never mind, after a little research it appears IE (all versions) do not and will not support base64 data uri encoding for data types other than images for security reasons. 

http://en.wikipedia.org/wiki/Data_URI_scheme

**Comment by manuels** [comment]
Oh, ok then. Thanks for doing the research! :+1:
